CREATE TABLE costume_item_photos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    production_id BIGINT NOT NULL,
    costume_item_id BIGINT NOT NULL,
    original_name TEXT NOT NULL
        CHECK (length(trim(original_name)) > 0
            AND original_name NOT IN ('.', '..')
            AND position('/' IN original_name) = 0
            AND position(chr(92) IN original_name) = 0),
    display_name TEXT NOT NULL
        CHECK (length(trim(display_name)) > 0
            AND display_name NOT IN ('.', '..')
            AND position('/' IN display_name) = 0
            AND position(chr(92) IN display_name) = 0),
    thumbnail_name TEXT NOT NULL
        CHECK (length(trim(thumbnail_name)) > 0
            AND thumbnail_name NOT IN ('.', '..')
            AND position('/' IN thumbnail_name) = 0
            AND position(chr(92) IN thumbnail_name) = 0),
    media_type TEXT NOT NULL CHECK (length(trim(media_type)) > 0),
    status TEXT NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending', 'ready', 'failed')),
    error_message TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (production_id, costume_item_id)
        REFERENCES costume_items (production_id, id) ON DELETE RESTRICT
);

CREATE INDEX idx_costume_item_photos_item
    ON costume_item_photos (production_id, costume_item_id, created_at, id);
CREATE INDEX idx_costume_item_photos_pending
    ON costume_item_photos (status, created_at, id)
    WHERE status = 'pending';
